name: releaseDeck
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACK_NAME: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.0
          cache: pip
          architecture: x64
      - name: Run
        run: |
          cd ./script/
          python -m pip install --upgrade pip
          python releaseDeck.py
          cd ..
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: ./target/deck/index.json
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
  with:
    add: '.'
    message: 'release deck index.json'
    push: true
    # remove: './deck/index.json'
    # tag_push: '--force'
